table fact_assessments
	lineageTag: 79b39747-9676-4d7d-a73a-9c60e2e31b40

	column course_id
		dataType: string
		lineageTag: f6c4c14b-20d1-4caf-b63a-7847b331186c
		summarizeBy: none
		sourceColumn: course_id
		annotation SummarizationSetBy = Automatic

	column assessment_date
		dataType: dateTime
		lineageTag: da7d5182-3db1-4f59-91dc-6051e9ba34dc
		summarizeBy: none
		sourceColumn: assessment_date
		annotation SummarizationSetBy = Automatic

	column assessment_type
		dataType: string
		lineageTag: 916460ec-6a75-40e8-8199-d53393006ba0
		summarizeBy: none
		sourceColumn: assessment_type
		annotation SummarizationSetBy = Automatic

	column students_attempted
		dataType: int64
		formatString: 0
		lineageTag: 86c50cd6-4f57-40fd-b853-64d5eb012787
		summarizeBy: sum
		sourceColumn: students_attempted
		annotation SummarizationSetBy = Automatic

	column avg_score_pct
		dataType: double
		formatString: #,0.00
		lineageTag: 26ca808e-51d9-4558-9b9e-1e5561bc9d44
		summarizeBy: average
		sourceColumn: avg_score_pct
		annotation SummarizationSetBy = Automatic

	column pass_rate
		dataType: double
		formatString: #,0.00
		lineageTag: f3d91c56-8a32-4139-93a8-adb21908155b
		summarizeBy: average
		sourceColumn: pass_rate
		annotation SummarizationSetBy = Automatic

	column top_scorers_pct
		dataType: double
		formatString: #,0.00
		lineageTag: df9112ea-3b2a-455f-ac65-70e0fb200108
		summarizeBy: average
		sourceColumn: top_scorers_pct
		annotation SummarizationSetBy = Automatic

	column avg_attempts
		dataType: double
		formatString: #,0.00
		lineageTag: b2d6eb12-34a2-42c6-88b4-1e8f8739cb24
		summarizeBy: average
		sourceColumn: avg_attempts
		annotation SummarizationSetBy = Automatic

	column avg_time_mins
		dataType: double
		formatString: #,0.00
		lineageTag: 0f30c21e-ded9-4aa0-85ab-a5510d43f755
		summarizeBy: average
		sourceColumn: avg_time_mins
		annotation SummarizationSetBy = Automatic

	partition fact_assessments = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\\DevOps\\rumana-portfolio\\powerbi-projects\\edtech-engagement\\data\\fact_assessments.csv"),
				        [Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"course_id", type text}, {"assessment_date", type date}, {"assessment_type", type text}, {"students_attempted", Int64.Type}, {"avg_score_pct", type number}, {"pass_rate", type number}, {"top_scorers_pct", type number}, {"avg_attempts", type number}, {"avg_time_mins", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation
	annotation PBI_ResultType = Table
