table dim_users
	lineageTag: e1a98f71-4c03-41e7-a168-f1a03fb8e805

	column user_id
		dataType: string
		lineageTag: 67f475ad-0294-4205-88f7-15e613629bff
		summarizeBy: none
		sourceColumn: user_id

		annotation SummarizationSetBy = Automatic

	column signup_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: c219745c-36a6-4932-a4b6-c9cd716480fa
		summarizeBy: none
		sourceColumn: signup_date

		variation Variation
			isDefault
			relationship: 7705d91e-275e-4a60-a88d-7630373ba320
			defaultHierarchy: LocalDateTable_e4371eb2-d7be-4eb8-aea5-7d5dfb9150d0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column age_group
		dataType: string
		lineageTag: d8e31376-0dfe-4d6d-9d45-21e8bf832442
		summarizeBy: none
		sourceColumn: age_group

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: 4303dbed-1cd3-46b0-99d1-3674ad3aac29
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 1a6ced7d-8eee-433d-b072-2aa64268f8e3
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column device_preference
		dataType: string
		lineageTag: cbdcec09-1875-4818-ac0b-acd997b7503e
		summarizeBy: none
		sourceColumn: device_preference

		annotation SummarizationSetBy = Automatic

	column loyalty_tier
		dataType: string
		lineageTag: aca0d05f-cceb-4571-af4c-6a3999ffdf9a
		summarizeBy: none
		sourceColumn: loyalty_tier

		annotation SummarizationSetBy = Automatic

	column is_new_user
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8f1e9b86-0c0a-4a5b-92fe-88c3a323110c
		summarizeBy: none
		sourceColumn: is_new_user

		annotation SummarizationSetBy = Automatic

	partition dim_users = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\DevOps\rumana-portfolio\powerbi-projects\product-funnel-dashboard\data\dim_users.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"user_id", type text}, {"signup_date", type date}, {"age_group", type text}, {"gender", type text}, {"region", type text}, {"device_preference", type text}, {"loyalty_tier", type text}, {"is_new_user", type logical}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

