table fact_wages
	lineageTag: c6abbc34-0df1-4323-af64-510468bee3e0

	column state_code
		dataType: string
		lineageTag: c3f0d024-a2e8-467e-8e19-96bdb6d3bf2b
		summarizeBy: none
		sourceColumn: state_code
		annotation SummarizationSetBy = Automatic

	column district_code
		dataType: string
		lineageTag: ce77bc89-214a-4f47-8a67-6b56099f5b47
		summarizeBy: none
		sourceColumn: district_code
		annotation SummarizationSetBy = Automatic

	column report_date
		dataType: dateTime
		lineageTag: 476d7967-77a4-453b-b1f4-6a058978e931
		summarizeBy: none
		sourceColumn: report_date
		annotation SummarizationSetBy = Automatic

	column financial_year
		dataType: string
		lineageTag: 45991407-b2df-442d-aeca-83de9672d87e
		summarizeBy: none
		sourceColumn: financial_year
		annotation SummarizationSetBy = Automatic

	column month_num
		dataType: int64
		formatString: 0
		lineageTag: 94be20cb-e5ea-4173-acfb-b56c7989f3ba
		summarizeBy: none
		sourceColumn: month_num
		annotation SummarizationSetBy = Automatic

	column workers_paid
		dataType: int64
		formatString: 0
		lineageTag: 84320114-cc31-4077-ba4b-d6625b8972e6
		summarizeBy: sum
		sourceColumn: workers_paid
		annotation SummarizationSetBy = Automatic

	column total_wages_lakhs
		dataType: double
		formatString: #,0.00
		lineageTag: d35b9276-f378-493b-9db7-977d8ba65f99
		summarizeBy: sum
		sourceColumn: total_wages_lakhs
		annotation SummarizationSetBy = Automatic

	column wages_within_15days_lakhs
		dataType: double
		formatString: #,0.00
		lineageTag: ba57cd5c-963b-4079-9559-048fd5deb3ba
		summarizeBy: sum
		sourceColumn: wages_within_15days_lakhs
		annotation SummarizationSetBy = Automatic

	column pending_wages_lakhs
		dataType: double
		formatString: #,0.00
		lineageTag: d98e3415-a81b-47d3-9695-4a5b12226141
		summarizeBy: sum
		sourceColumn: pending_wages_lakhs
		annotation SummarizationSetBy = Automatic

	column avg_wage_rate
		dataType: double
		formatString: #,0.00
		lineageTag: c2f3047e-9a8a-45b0-bcbd-fdaf8b88271c
		summarizeBy: average
		sourceColumn: avg_wage_rate
		annotation SummarizationSetBy = Automatic

	column notified_wage_rate
		dataType: double
		formatString: #,0.00
		lineageTag: 843eff7b-3c78-4d23-8492-4288ff4f540f
		summarizeBy: average
		sourceColumn: notified_wage_rate
		annotation SummarizationSetBy = Automatic

	partition fact_wages = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\\DevOps\\rumana-portfolio\\powerbi-projects\\nrega-analysis\\data\\fact_wages.csv"),
				        [Delimiter=",", Columns=11, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"state_code", type text}, {"district_code", type text}, {"report_date", type date}, {"financial_year", type text}, {"month_num", Int64.Type}, {"workers_paid", Int64.Type}, {"total_wages_lakhs", type number}, {"wages_within_15days_lakhs", type number}, {"pending_wages_lakhs", type number}, {"avg_wage_rate", type number}, {"notified_wage_rate", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation
	annotation PBI_ResultType = Table
