table fact_works
	lineageTag: a51fb21f-21e4-4061-b91c-ed45fcee9ab4

	column state_code
		dataType: string
		lineageTag: 4315bb6a-516b-4d7f-a9a7-a5584c0f5164
		summarizeBy: none
		sourceColumn: state_code
		annotation SummarizationSetBy = Automatic

	column district_code
		dataType: string
		lineageTag: 0e08aad6-e706-490e-a0d1-87c760d7afde
		summarizeBy: none
		sourceColumn: district_code
		annotation SummarizationSetBy = Automatic

	column financial_year
		dataType: string
		lineageTag: 10305555-3042-4082-9ef6-958c6022f44c
		summarizeBy: none
		sourceColumn: financial_year
		annotation SummarizationSetBy = Automatic

	column category_id
		dataType: string
		lineageTag: e3abac3e-f18a-4d4f-a2ce-eb40e7c5ec52
		summarizeBy: none
		sourceColumn: category_id
		annotation SummarizationSetBy = Automatic

	column report_date
		dataType: dateTime
		lineageTag: 8433ec7d-22ea-4d86-89ef-71a95acaf0b3
		summarizeBy: none
		sourceColumn: report_date
		annotation SummarizationSetBy = Automatic

	column works_taken_up
		dataType: int64
		formatString: 0
		lineageTag: 8a0bf84a-cf97-4c66-9b25-5d201975bfe7
		summarizeBy: sum
		sourceColumn: works_taken_up
		annotation SummarizationSetBy = Automatic

	column works_completed
		dataType: int64
		formatString: 0
		lineageTag: aa72a4d4-1d1b-4cec-b113-ace83b33e837
		summarizeBy: sum
		sourceColumn: works_completed
		annotation SummarizationSetBy = Automatic

	column works_in_progress
		dataType: int64
		formatString: 0
		lineageTag: 55bba48c-90c9-4a42-bb86-547ed1e9b0c0
		summarizeBy: sum
		sourceColumn: works_in_progress
		annotation SummarizationSetBy = Automatic

	column expenditure_lakhs
		dataType: double
		formatString: #,0.00
		lineageTag: e8dd5999-7afd-40bd-b553-c19c9ed2e203
		summarizeBy: sum
		sourceColumn: expenditure_lakhs
		annotation SummarizationSetBy = Automatic

	column assets_created
		dataType: int64
		formatString: 0
		lineageTag: 3054d151-6a49-440c-93e9-7c02a47167aa
		summarizeBy: sum
		sourceColumn: assets_created
		annotation SummarizationSetBy = Automatic

	partition fact_works = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\\DevOps\\rumana-portfolio\\powerbi-projects\\nrega-analysis\\data\\fact_works.csv"),
				        [Delimiter=",", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"state_code", type text}, {"district_code", type text}, {"financial_year", type text}, {"category_id", type text}, {"report_date", type date}, {"works_taken_up", Int64.Type}, {"works_completed", Int64.Type}, {"works_in_progress", Int64.Type}, {"expenditure_lakhs", type number}, {"assets_created", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation
	annotation PBI_ResultType = Table
